// Code generated by "stringer -type=BugType"; DO NOT EDIT

package main

import "fmt"

const _BugType_name = "BugSmallBugLargeBugGnatBugMagicBugBombBugLightningBugRockBugMultiChain"

var _BugType_index = [...]uint8{0, 8, 16, 23, 31, 38, 50, 57, 70}

func (i BugType) String() string {
	if i >= BugType(len(_BugType_index)-1) {
		return fmt.Sprintf("BugType(%d)", i)
	}
	return _BugType_name[_BugType_index[i]:_BugType_index[i+1]]
}
